apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: analyzer
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analyzer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: analyzer
    spec:
      containers:
        - args:
            - anchore-manager
            - service
            - start
            - analyzer
          env:
            - name: ANCHORE_ADMIN_PASSWORD
              value: foobar
            - name: ANCHORE_DB_HOST
              value: db
            - name: ANCHORE_DB_PASSWORD
              value: mysecretpassword
            - name: ANCHORE_ENDPOINT_HOSTNAME
              value: analyzer
          image: anchore/anchore-engine:v1.0.0
          name: analyzer
          ports:
            - containerPort: 8228
          resources: {}
          volumeMounts:
            - mountPath: /analysis_scratch
              name: analyzer-claim0
      restartPolicy: Always
      volumes:
        - name: analyzer-claim0
          persistentVolumeClaim:
            claimName: analyzer-claim0
status: {}
